### ISSUE TITLE
VideoCalling on React Native?

### ISSUE THREAD

**Issue by zek** [ConnectyCube/connectycube-js-samples#9]
I guess there is no video calling feature in connectycube-reactnative  

ConnectyCube.videochat is false. Isn't implemented or I am making a mistake?

**Comment by DaveLombardo** [comment]
Hi @zek 
At this moment everything is supported except VideoChat API
We have it in our roadmap and will add soon

Our idea is to integrate https://github.com/oney/react-native-webrtc into our SDK

**Comment by zek** [comment]
If I integrate it to react-native-webrtc to my project, Is it works? As I see you are checking a few window.variables and react-native-webrtc defines those variables.

**Comment by DaveLombardo** [comment]
Our SDK uses standard WebRTC API, e.g:

* navigator.mediaDevices.getUserMedia
* window.RTCPeerConnection;
* window.RTCSessionDescription;
* window.RTCIceCandidate;


so if they are defined then it will work

**Comment by zek** [comment]
I guess I am able to add this library but now I have another problem.
When I check what's inside in jid, I see it is an array not a string so indexOf is not defined.
 {
  "_domain": "chat.connectycube.com",
  "_local": "32230-154",
  "_resource": "1204607085-chat-284052",
}

~~~
[20:05:39] jid.indexOf is not a function. (In 'jid.indexOf('@')', 'jid.indexOf' is undefined)
- node_modules/connectycube-reactnative/src/videocalling/cubeWebRTCHelpers.js:13:24 in getIdFromNode
- node_modules/connectycube-reactnative/src/videocalling/cubeWebRTCClient.js:120:45 in _createAndStoreSession
* store/cb_store.js:62:60 in <unknown>
- node_modules/connectycube-reactnative/src/messaging/cubeChat.js:865:29 in <unknown>
- node_modules/connectycube-reactnative/src/messaging/cubeChat.js:1016:25 in <unknown>
~~~


~~~
			var userCredentials = {login: 'login', password: 'password'};

			ConnectyCube.createSession(userCredentials, function (error, session) {
				let userId = session.user_id;

				//let jid = ConnectyCube.chat.helpers.getUserJid(userId, 154);

				var userCredentials = {userId, password: 'password'};
				ConnectyCube.chat.connect(userCredentials, function(error, contactList) {
					if(!error){
						var calleesIds = [32231]; // User's ids
						var sessionType = ConnectyCube.videochat.CallType.AUDIO; // AUDIO is also possible
						var additionalOptions = {};

						var session = ConnectyCube.videochat.createNewSession(calleesIds, sessionType, additionalOptions);

					}
				});

			});

~~~

**Comment by zek** [comment]
And also I wonder how can we use this elementId thing.

var mediaParams = {
  audio: true,
  video: true,
  elementId: 'myVideoElementId' // ID of audio/video DOM element to attach a video stream to
};

**Comment by zek** [comment]
Do you planning give support webrtc for react native?

**Comment by DaveLombardo** [comment]
'elementId' is an option.
If it's not passed - then you need to manually attach a stream to UI. So it's more like a helper, but not required

**Comment by lherman-cs** [comment]
Is there any update about this? @zek did you figure out attaching a stream to UI with react-native?

**Comment by DaveLomber** [comment]
@lherman-cs we actively working on it, SDK & code sample will be released in a couple of days

**Comment by lherman-cs** [comment]
@DaveLomber I'm sorry to ask again. How's the update? It has been a couple of days. 

My client really needs this feature. If this update still takes a while, I would definitely start looking at integrating https://github.com/oney/react-native-webrtc into my stack instead. Thanks

**Comment by DaveLomber** [comment]
@DaveLomber yes, 
I will provide today an info what we have so you can start

we incorporated a react-native-webrtcpackage into our sdk

**Comment by DaveLomber** [comment]
hey @lherman-cs 

we have pushed a working branch with RN video example
https://github.com/ConnectyCube/connectycube-js-samples/tree/feature/rn-video/RNVideoChat

also beta version of SDK is there

There is still some work to finish which we are heavily working on right now

But you can already start integrating it in your app.

Basically the Video Chat API is pretty the same we have for JS Web
https://developers.connectycube.com/js/videocalling

the only one diff thing is video view rendering which you can whack in our sample already 

We will keep you posted on future updates

let us also know if there are any issues/questions so far

**Comment by lherman-cs** [comment]
@DaveLomber I'm trying to integrate the videochat SDK into our project. But, I keep getting this error, `null is not an object (evaluating 'client.jid._local')` whenever I tried to `createNewSession`

**Comment by lherman-cs** [comment]
also, where is the `connectycube-reactnative-1.6.6.tgz`?

**Comment by DaveLomber** [comment]
Hi @lherman-cs 

sorry for this inconvenience 
we have pushed a connectycube-reactnative-1.6.7.tgz, which does not have the issue you mentioned
and also pushed more updates to code sample
so the basic functionality with call/accept/reject & users stream display is here


please let us know if you have any other issues or need help with the integration

**Comment by lherman-cs** [comment]
Hi, I'm still getting the same error, `null is not an object (evaluating 'client.jid._local')`. Below is the stacktrace

<img width="303" alt="Screen Shot 2019-03-27 at 11 44 41 AM" src="https://user-images.githubusercontent.com/15654932/55090562-b9d30e80-5085-11e9-8f06-a77cb90bac18.png">

**Comment by DaveLomber** [comment]
@lherman-cs  one thing to check - did you connect with this user to chat ?

https://github.com/ConnectyCube/connectycube-js-samples/blob/feature/rn-video/RNVideoChat/src/components/AuthScreen/AuthForm.js#L27

because in a WebRTC stack we access a current user connected to Chat, since we use a Chat channel as a signaling channel for video calls, so a user should be connected to Chat in order to create a video session 

Could you please check this part and let us know

**Comment by lherman-cs** [comment]
So, I have to connect to the chat first, even after the user is logged in using `ConnectyCube.login(userCredentials, function(error, user)`?

**Comment by lherman-cs** [comment]
I've connected the user to the chat. But, then I got the following:

```
03-27 12:51:11.359 27097 27139 I ReactNativeJS: { name: 'SecurityError',
03-27 12:51:11.359 27097 27139 I ReactNativeJS:   message: 'Permission denied.',
03-27 12:51:11.359 27097 27139 I ReactNativeJS:   constraintName: undefined }
```

**Comment by DaveLomber** [comment]
@lherman-cs 
yes, the first one is to create a session token to access REST API

and CHAT is a real-time channel to send/receive messages in a real time, 
need to connect as well

**Comment by DaveLomber** [comment]
@lherman-cs on permissions - it successfully works on IOS w/o any additional permissions 

On Android - please use this one https://facebook.github.io/react-native/docs/permissionsandroid

**Comment by lherman-cs** [comment]
Is it only camera permission that connectycube needs for android?

**Comment by lherman-cs** [comment]
I've added these permissions to the `AndroidManifest.xml`

```
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

However, after I got the camera permission, it gave me the following error:

`TypeError: null is not an object (evaluating 'WebRTCModule.getUserMedia')`

**Comment by DaveLomber** [comment]
@lherman-cs  we are double checking it right now

**Comment by DaveLomber** [comment]
@lherman-cs since we use react-native-webrtc lib inside, hence need to configure our project:

Android https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

iOS https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

we are adding all these to this code sample, should be ready soon

**Comment by DaveLomber** [comment]
@lherman-cs  an Android project configuration has been pushed, please try at your end and let us know

**Comment by lherman-cs** [comment]
@DaveLomber I've just successfully installed the webrtc library for android. Now, I'm trying to get the stream's URL by using `stream.toURL()` (stream is the object that `session.getUserMedia` returns). When I printed this out, the url is `ae378074-489f-4bab-ace5-88bf0ca06b5e`. Is this expected? Because it doesn't look like a url to me.

**Comment by DaveLomber** [comment]
@lherman-cs I never printed this value, just pass it to the RTCView directly, so I guess this is ok
does it display your video stream?

**Comment by JuAlexandre** [comment]
I'm facing the same problem, `ConnectyCube.videochat` is `false` ...
I reproduced the code of the demo in my project and I installed `react-native-webrtc` for iOS and Android.
I do not see where there can be a problem ...

**Comment by DaveLomber** [comment]
@JuAlexandre please try exactly this branch and this local sdk build
https://github.com/ConnectyCube/connectycube-js-samples/blob/feature/rn-video/RNVideoChat/connectycube-reactnative-1.6.7.tgz

It's still not pushed to the global npm registry, we are working to make it happen soon

**Comment by JuAlexandre** [comment]
Thanks for your quick reply my problem is solved!

**Comment by lherman-cs** [comment]
@DaveLomber the RTCView is showing my camera view so far. 

As the opponent, do I need to connect to the chat first?

**Comment by DaveLomber** [comment]
@lherman-cs yes, since Video Chat uses Chat connection for signaling, so you need to be connected.

Usually, the flow is the following:
1) User logins to an app (here we create a session to obtain a session toke, and also then connect to real time chat)
2) User is ready to initiate/receive calls

Also, when other party is offline, we can send a push along with a call request

**Comment by lherman-cs** [comment]
It seems that I missed something. I've followed the flow, but the callback still didn't get called.

**Comment by DaveLomber** [comment]
@lherman-cs the things to check:
1) does an opponent (UserB) is connected to Chat at that time where UserA is calling?
2) at UserB side, do you see anything in logs at that time where UserA is calling?
3) Does an 'opponentsIds' set correctly when you create a video session. should be set to an array of a single id, id of a UserB

**Comment by lherman-cs** [comment]
1. UserB has been connected to chat
2. No, I'm not seeing any log
3. It's already in an array of numbers, the ids are also properly set according to the database

**Comment by lherman-cs** [comment]
Do I need to request camera permission first?

**Comment by DaveLomber** [comment]
@lherman-cs could you double check our latest code sample provided, with those users https://github.com/ConnectyCube/connectycube-js-samples/tree/feature/rn-video/RNVideoChat

It has all needed settings and works well at your side.

Wwhen integrate a ConnectyCube RN SDK into your app,
 since we use react-native-webrtc lib inside, hence need to configure your project:

Android https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

iOS https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

We have these configurations in our code sample 

Please try out stock code sample and post here does it work at your side.
If yes - then will try to identify what's wrong with your app

**Comment by lherman-cs** [comment]
@DaveLomber The example can't run. Below is the screenshot.

<img width="937" alt="Screen Shot 2019-04-03 at 10 36 00 AM" src="https://user-images.githubusercontent.com/15654932/55487559-55233100-55fc-11e9-87f0-09dc9ab378eb.png">

**Comment by DaveLomber** [comment]
@lherman-cs just ran and faced the same..

Android development on React Native can be painny sometimes..

but I revised all the dependencies, and now it works like a charm

please check my 2 latest commits

Here is a list of dependencies versions that works well:

- react-native 0.59.2 (set in package.json)
- react 16.8.3 (set in package.json)
- gradle 4.10.1 (set in android/gradle/wrapper/gradle-wrapper.properties)
- Android Studio 3.3.2 
- gradle plugin 3.3.0 (set in android/build.gradle)

Please pull the latest changes and try to run the sample again (remove node_modules and package-lock.json and do 'npm install' before it)

**Comment by lherman-cs** [comment]
Somehow I got this error now.
<img width="274" alt="Screen Shot 2019-04-03 at 1 08 18 PM" src="https://user-images.githubusercontent.com/15654932/55498430-996cfc00-5611-11e9-8f86-5fd1641cdd9a.png">

**Comment by lherman-cs** [comment]
nvm, I fixed this. But, I've matched the dependencies. But, the callback still never got called...

**Comment by lherman-cs** [comment]
I tried to follow what the example has in setting up the listener, https://github.com/ConnectyCube/connectycube-js-samples/blob/feature/rn-video/RNVideoChat/src/components/Root.js#L29. But, it always gives me `TypeError: undefined is not an object (evaluating '_connectycubeReactnative.default.videochat`

**Comment by DaveLomber** [comment]
@lherman-cs 
1) you use latest connectycube-reactnative-1.6.9.tgz , right? 
2) make sure the very first thing you call  is 'ConnectyCube.init'

I nothing works - could you please share more stack trace

**Comment by lherman-cs** [comment]
1. Yes
2. I did this in my root app already

At this moment, I'm not sure which stacktrace that I should provide. But, following is the `ConnectyCube` object after:
1. Login
2. Connect to chat

```
04-03 14:52:38.324  6006  6043 I ReactNativeJS: { connection: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:    { _events: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:       { disconnect: [ [Function], [Function: callbackDisconnect] ],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         element: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         connect: [Function: callbackConnect],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         online: [Function: callbackOnline],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         offline: [Function: callbackOffline],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         status: [Function: callbackStatus],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         stanza: [Function: callbackStanza],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         error: [Function: callbackError],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         output: [Function: callbackOutput],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         input: [Function: callbackInput] },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      _eventsCount: 10,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      _maxListeners: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      domain: 'chat.connectycube.com',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      lang: 'en',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      jid: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:       { _domain: 'chat.connectycube.com',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         _local: '93872-345',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         _resource: '1204607085-chat-277123' },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      timeout: 2000,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      options: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:       { service: 'wss://chat.connectycube.com:5291',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         domain: 'chat.connectycube.com' },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      socketListeners: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:       { data: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         close: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         connect: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         error: [Function] },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      parserListeners: { element: [Function], error: [Function], end: [Function] },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      status: 'online',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:      socket: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:       { _events: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:          { close: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            data: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            error: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            connect: [Function] },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         _eventsCount: 4,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         _maxListeners: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         listeners: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:          { open: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            message: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            error: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            close: [Function] },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         url: 'wss://chat.connectycube.com:5291',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:         socket: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:          { CONNECTING: 0,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            OPEN: 1,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            CLOSING: 2,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            CLOSED: 3,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            readyState: 1,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:            _eventEmitter: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:             { _subscriber: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                { _subscriptionsForType: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                   { appStateDidChange: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                      [ { subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          emitter: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                           { _subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                             isAvailable: true,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                             _eventHandlers: { change: {}, memoryWarning: {} },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                             currentState: 'active' },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          listener: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          context: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          eventType: 'appStateDidChange',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          key: 0 } ],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                     websocketMessage: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                      [ ,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                        { subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          emitter: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          listener: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          context: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          eventType: 'websocketMessage',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          key: 1 } ],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                     websocketOpen: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                      [ ,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                        { subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          emitter: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          listener: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          context: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          eventType: 'websocketOpen',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          key: 1 } ],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                     websocketClosed: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                      [ ,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                        { subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          emitter: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          listener: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          context: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          eventType: 'websocketClosed',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          key: 1 } ],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                     websocketFailed: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                      [ ,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                        { subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          emitter: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          listener: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          context: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          eventType: 'websocketFailed',
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          key: 1 } ],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                     didUpdateDimensions: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                      [ { subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          emitter: 
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                           { _subscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                             sharedSubscriber: [Circular],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                             _currentSubscription: null },
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          listener: [Function],
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          context: undefined,
04-03 14:52:38.324  6006  6043 I ReactNativeJS:                          event
```

**Comment by lherman-cs** [comment]
@DaveLomber I just realized that I can turn on the debug flag in connectycube, 😆.

Here is the stacktrace from connectycube

```
04-03 15:01:52.503  6437  6472 I ReactNativeJS: '[Request][1]', 'POST https://api.connectycube.com/session.json', { application_id: 345,
04-03 15:01:52.503  6437  6472 I ReactNativeJS:   auth_key: 'E7brJd48VRLZbKF',
04-03 15:01:52.503  6437  6472 I ReactNativeJS:   nonce: 9179,
04-03 15:01:52.503  6437  6472 I ReactNativeJS:   timestamp: 1554318112,
04-03 15:01:52.503  6437  6472 I ReactNativeJS:   signature: '5d5b320a28928f2f9744b43026f7dc78cf3af16b' }
04-03 15:01:52.722  6437  6472 I ReactNativeJS: '[Response][1]', { session: 
04-03 15:01:52.722  6437  6472 I ReactNativeJS:    { id: 612100,
04-03 15:01:52.722  6437  6472 I ReactNativeJS:      user_id: 0,
04-03 15:01:52.722  6437  6472 I ReactNativeJS:      application_id: 345,
04-03 15:01:52.722  6437  6472 I ReactNativeJS:      nonce: 9179,
04-03 15:01:52.722  6437  6472 I ReactNativeJS:      token: '33cdb0baeb862ca70fc919a25a04a8ce2a000159',
04-03 15:01:52.722  6437  6472 I ReactNativeJS:      ts: 1554318112,
04-03 15:01:52.722  6437  6472 I ReactNativeJS:      created_at: '2019-04-03T19:01:53Z',
04-03 15:01:52.722  6437  6472 I ReactNativeJS:      updated_at: '2019-04-03T19:01:53Z' } }
04-03 15:01:52.723  6437  6472 I ReactNativeJS: '[Request][2]', 'POST https://api.connectycube.com/login.json', { login: 'poop', password: 'pooppoop' }
04-03 15:01:52.796  6437  6472 I ReactNativeJS: '[Response][2]', { user: 
04-03 15:01:52.796  6437  6472 I ReactNativeJS:    { id: 93872,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      full_name: null,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      email: null,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      login: 'poop',
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      phone: '',
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      website: null,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      created_at: '2019-04-03T03:52:13Z',
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      updated_at: '2019-04-03T03:52:13Z',
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      last_request_at: '2019-04-03T19:01:53Z',
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      external_user_id: null,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      facebook_id: null,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      twitter_id: null,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      blob_id: null,
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      custom_data: '{"gender":"male","approved":false,"languages":[{"name":"english","proficiency":"native"}],"relevant_experience":"I\'m a pro","relevant_courses":"ENGL 3150","schedule":{"weekly":{"mon":[{"start":"1899-12-31T13:00:00.000Z","end":"1900-01-01T01:00:00.000Z"}]}}}',
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      avatar: '',
04-03 15:01:52.796  6437  6472 I ReactNativeJS:      user_tags: null } }
04-03 15:01:55.411  6437  6472 I ReactNativeJS: '[Chat]', 'Connect with parameters {"userId":93872,"password":"pooppoop"}'
04-03 15:01:55.412  6437  6472 I ReactNativeJS: '[Chat]', 'status', 'connecting', ''
04-03 15:01:55.625  6437  6472 I ReactNativeJS: '[Chat]', 'status', 'connect', ''
04-03 15:01:55.625  6437  6472 I ReactNativeJS: '[Chat]', 'CONNECTING'
04-03 15:01:55.626  6437  6472 I ReactNativeJS: '[Chat]', 'status', 'opening', ''
04-03 15:01:55.630  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<open version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="chat.connectycube.com"/>'
04-03 15:01:55.692  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<open xmlns=\'urn:ietf:params:xml:ns:xmpp-framing\' from=\'chat.connectycube.com\' id=\'bd628d88-3012-44b3-b411-1e3df61ba3c8\' version=\'1.0\' xml:lang=\'en\' />'
04-03 15:01:55.695  6437  6472 I ReactNativeJS: '[Chat]', 'status', 'open', '<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" from="chat.connectycube.com" id="bd628d88-3012-44b3-b411-1e3df61ba3c8" version="1.0" xml:lang="en"/>'
04-03 15:01:55.699  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>'
04-03 15:01:55.707  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">ADkzODcyLTM0NQBwb29wcG9vcA==</auth>'
04-03 15:01:55.774  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>'
04-03 15:01:55.776  6437  6472 I ReactNativeJS: '[Chat]', 'status', 'opening', ''
04-03 15:01:55.776  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<open version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="chat.connectycube.com"/>'
04-03 15:01:55.838  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<open xmlns=\'urn:ietf:params:xml:ns:xmpp-framing\' from=\'chat.connectycube.com\' id=\'bd628d88-3012-44b3-b411-1e3df61ba3c8\' version=\'1.0\' xml:lang=\'en\' />'
04-03 15:01:55.840  6437  6472 I ReactNativeJS: '[Chat]', 'status', 'open', '<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" from="chat.connectycube.com" id="bd628d88-3012-44b3-b411-1e3df61ba3c8" version="1.0" xml:lang="en"/>'
04-03 15:01:55.842  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>'
04-03 15:01:55.845  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<iq type="set" id="v455v27xiaa" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/></iq>'
04-03 15:01:55.909  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<iq xmlns="jabber:client" id="v455v27xiaa" to="93872-345@chat.connectycube.com/1204607085-chat-277150" type="result"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>93872-345@chat.connectycube.com/1204607085-chat-277150</jid></bind></iq>'
04-03 15:01:55.917  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<iq type="set" id="ioftepb3ow9" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq>'
04-03 15:01:55.918  6437  6472 I ReactNativeJS: '[Chat]', 'status', 'online', '93872-345@chat.connectycube.com/1204607085-chat-277150'
04-03 15:01:55.918  6437  6472 I ReactNativeJS: '[Chat]', 'ONLINE'
04-03 15:01:55.918  6437  6472 I ReactNativeJS: '[Chat]', 'CONNECTED'
04-03 15:01:55.920  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<iq type="set" from="93872-345@chat.connectycube.com/1204607085-chat-277150" id="f1a1aca8-07ae-4e75-ab8f-9cb182477693:enableCarbons" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/></iq>'
04-03 15:01:55.920  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<iq type="get" from="93872-345@chat.connectycube.com/1204607085-chat-277150" id="5be59c0d-91a7-450e-8657-848714accd74:getRoster" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/></iq>'
04-03 15:01:55.978  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<iq xmlns="jabber:client" id="ioftepb3ow9" to="93872-345@chat.connectycube.com/1204607085-chat-277150" type="result"/>'
04-03 15:01:55.980  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<iq xmlns="jabber:client" id="f1a1aca8-07ae-4e75-ab8f-9cb182477693:enableCarbons" to="93872-345@chat.connectycube.com/1204607085-chat-277150" type="result"/>'
04-03 15:01:55.981  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<iq xmlns="jabber:client" id="5be59c0d-91a7-450e-8657-848714accd74:getRoster" to="93872-345@chat.connectycube.com/1204607085-chat-277150" type="result"><query xmlns="jabber:iq:roster"/></iq>'
04-03 15:01:55.984  6437  6472 I ReactNativeJS: '[Chat]', 'SENT:', '<presence xmlns="jabber:client"/>'
04-03 15:01:56.050  6437  6472 I ReactNativeJS: '[Chat]', 'RECV:', '<presence to="93872-345@chat.connectycube.com" from="93872-345@chat.connectycube.com/1204607085-chat-277150" xmlns="jabber:client"/>'
```

**Comment by DaveLomber** [comment]
@lherman-cs I see you successfully connected to Chat 

Try to do like `console.log(ConnectyCube.videochat)` before setting a `ConnectyCube.videochat.onCallListener`, just curious what's there.

**Comment by lherman-cs** [comment]
The previous comment, https://github.com/ConnectyCube/connectycube-js-samples/issues/9#issuecomment-479615898, is actually the output from `console.log(ConnectyCube.videochat)`

**Comment by DaveLomber** [comment]
@lherman-cs ok nevermind, so it's all looks good then. 


So again, it crashes somewhere inside Connectycube SDK when you run this line
`ConnectyCube.videochat.onCallListener = this.onCallListener.bind(this);` , am I understood it correct?
if not, then at which point it crashes?

**Comment by lherman-cs** [comment]
@DaveLomber it never crashed. It's just after I set the callback, the callback never got called after I tried to call the opponent.

**Comment by DaveLomber** [comment]
@lherman-cs in a case you can share you prog so we will check at our side - please share to 'admin' at 'connectycube.com'

**Comment by lherman-cs** [comment]
@DaveLomber I'm sorry! I just made a very stupid mistake... I had a function call "call", but in that function, I forgot to actually call the real "call" function.... 😆

**Comment by lherman-cs** [comment]
The callback finally got called now. But, I'm getting this error now, 

```
04-04 12:47:00.474  9219  9256 W ReactNativeJS: '[VideoChat]:', 'Invalid type of "extension" object.'
04-04 12:47:00.477  9219  9256 I ReactNativeJS: '[VideoChat]:', 'Accept, extension: undefined'
```

**Comment by lherman-cs** [comment]
is this an error on the caller or the receiver side?

**Comment by lherman-cs** [comment]
The callback finally got called. Now, I'm getting this error. Do you have any idea the cause?

```
Error in listener _cb: TypeError: self._clearAnswerTimer is not a function. (In 'self._clearAnswerTimer()', 'self._clearAnswerTimer' is undefined)
```

**Comment by lherman-cs** [comment]
nvm, with my comment above. Apparently, there's a problem with my backend. After, I replace with the raw callback, it works fine. 

But, now, I got this error:
<img width="298" alt="Screen Shot 2019-04-04 at 1 21 05 PM" src="https://user-images.githubusercontent.com/15654932/55575281-86732e00-56dc-11e9-8056-a3ad974fd7e8.png">

**Comment by DaveLomber** [comment]
@lherman-cs which 'session' object you use when you call `session.accept()` ?
You should use the one that you get in a `ConnectyCube.videochat.onCallListener` listener.

When accept a call you do not need to create a new session, but use the one that you get in a `ConnectyCube.videochat.onCallListener` listener.

Please double check it

JS Video Chat documentation is available here https://developers.connectycube.com/js/videocalling?id=initiate-a-call

**Comment by lherman-cs** [comment]
@DaveLomber yes, I'm using the session from onCallListener. Below is the stacktrace for a scenario where userA (id: 92434) calls userB (id: 94681):

```
04-04 15:28:43.769  8078  8117 I ReactNativeJS: '[VideoChat]:', 'onCall. UserID:92434. SessionID: bee608e7-aa4c-4f87-b300-4bed40996de1'
04-04 15:28:43.850  8078  8117 I ReactNativeJS: { ID: 'bee608e7-aa4c-4f87-b300-4bed40996de1',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   state: 1,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   initiatorID: 92434,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   opponentsIDs: [ 94681 ],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   callType: NaN,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   peerConnections: {},
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   localStream: null,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   mediaParams: null,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:   signalingProvider: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:    { service: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:       { sdkInstance: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:          { config: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:             { version: '1.5.0',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               creds: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                { appId: 345,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  authKey: 'E7brJd48VRLZbKF',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  authSecret: 'gy6T6KwwBsC99tO' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               endpoints: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                { api: 'api.connectycube.com',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  chat: 'chat.connectycube.com',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  muc: 'muc.chat.connectycube.com' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               hash: 'sha1',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               chatProtocol: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                { bosh: 'https://chat.connectycube.com:5281',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  websocket: 'wss://chat.connectycube.com:5291',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  active: 2 },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               webSession: { getSessionTimeInterval: 3, getSessionTimeout: 120 },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               chat: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                { contactList: { subscriptionMode: { mutual: true } },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  reconnectionTimeInterval: 5,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  streamManagement: { enable: false } },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               videochat: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                { answerTimeInterval: 60,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  dialingTimeInterval: 5,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  disconnectTimeInterval: 30,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  statsReportTimeInterval: false,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  iceServers: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                   [ { urls: 'stun:stun.l.google.com:19302' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                     { urls: 'stun:turn.connectycube.com' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                     { urls: 'turn:turn.connectycube.com:5349?transport=udp',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                       username: 'connectycube',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                       credential: '4c29501ca9207b7fb9c4b4b6b04faeb1' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                     { urls: 'turn:turn.connectycube.com:5349?transport=tcp',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                       username: 'connectycube',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                       credential: '4c29501ca9207b7fb9c4b4b6b04faeb1' } ] },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               urls: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                { session: 'session',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  webSession: 'session/web',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  login: 'login',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  users: 'users',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  chat: 'chat',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  blobs: 'blobs',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  subscriptions: 'subscriptions',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  events: 'events',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  data: 'data',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  addressbook: 'address_book',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  addressbookRegistered: 'address_book/registered_users',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:                  type: '.json' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               on: { sessionExpired: null },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               timeout: null,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               debug: { mode: 1 },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               set: [Function] },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            session: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:             { id: 617577,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               user_id: 0,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               application_id: 345,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               nonce: 2461,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               token: 'ccc8ae2cd4f7442b04e8854f07f4682106000159',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               ts: 1554406084,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               created_at: '2019-04-04T19:28:05Z',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:               updated_at: '2019-04-04T19:28:05Z' } },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         currentUserId: 94681,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         reqCount: 2 },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:      connection: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:       { _events: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:          { disconnect: [ [Function], [Function: callbackDisconnect] ],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            element: [Function],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            connect: [Function: callbackConnect],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            online: [Function: callbackOnline],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            offline: [Function: callbackOffline],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            status: [Function: callbackStatus],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            stanza: [Function: callbackStanza],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            error: [Function: callbackError],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            output: [Function: callbackOutput],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            input: [Function: callbackInput] },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         _eventsCount: 10,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         _maxListeners: undefined,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         domain: 'chat.connectycube.com',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         lang: 'en',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         jid: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:          { _domain: 'chat.connectycube.com',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            _local: '94681-345',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            _resource: '1204607085-chat-281389' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         timeout: 2000,
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         options: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:          { service: 'wss://chat.connectycube.com:5291',
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            domain: 'chat.connectycube.com' },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         socketListeners: 
04-04 15:28:43.850  8078  8117 I ReactNativeJS:          { data: [Function],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            close: [Function],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            connect: [Function],
04-04 15:28:43.850  8078  8117 I ReactNativeJS:            error: [Function] },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         parserListeners: { element: [Function], error: [Function], end: [Function] },
04-04 15:28:43.850  8078  8117 I ReactNativeJS:         sta
04-04 15:28:43.851  8078  8117 I ReactNativeJS: '[VideoChat]:', 'Accept, extension: {}'
04-04 15:28:43.853  8078  8117 E ReactNativeJS: '[VideoChat]:', 'Can\'t accept the call, there is no information about peer connection by some reason.'
```

**Comment by DaveLomber** [comment]
@lherman-cs I see
this damn strange that ` peerConnections: {},` is empty, cause it should contain at least 1 value, a value of a call initiator, so this is why we see this error. But I newer saw anything like this. 


Can you please print the following things when you receive a call request:

```
console.log("initiatorID", session.initiatorID);
console.log("currentUserID", session.currentUserID);
console.log("opponentsIDs", session.opponentsIDs);
```  

and post here an output

**Comment by lherman-cs** [comment]
here it is
```
04-04 16:27:43.002  8458  8495 I ReactNativeJS: 'initiatorID', 92434
04-04 16:27:43.002  8458  8495 I ReactNativeJS: 'currentUserID', 94681
04-04 16:27:43.003  8458  8495 I ReactNativeJS: 'opponentsIDs', [ 94681 ]
```

**Comment by lherman-cs** [comment]
@DaveLomber I found that `WebRTCSession.prototype._acceptInternal` is called before `WebRTCClient.prototype._onCallListener` delegation got called.

**Comment by DaveLomber** [comment]
@lherman-cs thanks
hmm...
I'm just thinking how is that possible 
because you can't accept a call before a call request arrived, this is just impossible to do using our flow 
Let me double check everything.

**Comment by DaveLomber** [comment]
@lherman-cs while we are checking

Please double check your app code, that you use the following flow that is documented here

https://developers.connectycube.com/js/videocalling?id=initiate-a-call

**Comment by lherman-cs** [comment]
@DaveLomber Yes, I followed the flow in that documentation and also from your old comment.

The screenshot below is my code.

the `on` method is just a wrapper of the callbacks. And, the session is wrapped by my custom class. 

![Screenshot_2019-04-06_12-08-04](https://user-images.githubusercontent.com/15654932/55672059-8dc54380-5864-11e9-9f4c-5cf2c989f5f2.png)

**Comment by DaveLomber** [comment]
@lherman-cs ahaa
I think I got it

So you implement something like auto accept feature
and yes, I see an issue with it

If you accept a call after some delay after a call request is received then all is ok 

Will address it and let you know 

thanks for reporting!

**Comment by DaveLomber** [comment]
@lherman-cs 1.6.10 is here with the fix
you can try https://github.com/ConnectyCube/connectycube-js-samples/blob/feature/rn-video/RNVideoChat/connectycube-reactnative-1.6.10.tgz

**Comment by DaveLomber** [comment]
For all, 
we have released connectycube-reactnative-1.7.2 version, the first release with Video API support so now you can connect it globally:

>  "connectycube-reactnative": "1.7.2"

Further documentation will be provided soon 

@lherman-cs the custom branch is removed so now you can use a master brunch 

In a case of any issues - please create a new issue

thanks everybody for your support!

**Comment by lherman-cs** [comment]
@DaveLomber I've just updated the library to `1.7.2`. The previous issue is gone now. But, now, I have another problem where my `onRemoteStreamListener` never got called.

Below is the stacktrace:

```
04-08 13:19:16.226 13524 13563 I ReactNativeJS: Accepted call request
04-08 13:19:16.240 13524 13563 I ReactNativeJS: You can use the camera
04-08 13:19:16.313 13524 13563 I ReactNativeJS: '[VideoChat]:', 'Accept, extension: {}'
04-08 13:19:16.313 13524 13563 I ReactNativeJS: '[VideoChat]:', '_clearAnswerTimer'
04-08 13:19:16.363 13524 13563 I ReactNativeJS: '[VideoChat]:', '\'setRemoteSessionDescription\' success'
04-08 13:19:16.852 13524 13563 I ReactNativeJS: '[VideoChat]:', 'onIceCandidates. UserID:92434. SessionID: e31bdfb0-9603-4357-b195-cc3cb93cfb0e. ICE candidates count: 9'
04-08 13:19:16.863 13524 13563 I ReactNativeJS: '[VideoChat]:', 'onIceConnectionStateCallback: checking'
04-08 13:19:16.902 13524 13563 I ReactNativeJS: '[VideoChat]:', 'onIceConnectionStateCallback: connected'
```

**Comment by DaveLomber** [comment]
@lherman-cs a quick one to check
do you provide a call type when create a session?

like this:

```
const sessionType = ConnectyCube.videochat.CallType.VIDEO; // AUDIO is also possible
const additionalOptions = {};
const session = ConnectyCube.videochat.createNewSession(calleesIds, sessionType, additionalOptions);
```

**Comment by lherman-cs** [comment]
When I created the interface for this part in Typescript, I put `Video` instead of `VIDEO`. hahaha
